language: python
python:
- 3.7-dev
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: urbas
  password:
    secure: eQgcJev51+P01KxHQSm8tMclOJihlvEkLj5PsQfJwlO9X4/Qbdiwz7M2FcXC7YxohDErTT/TMF3vZkN3sPWr7KUS31042CUCf/gp9Zw5itWkBSRplnVJsVU2M0ecKErSrnUr8FO+7Q9IzJKAVJfXhNwFUUA3iflsQQZwSCGXSjyhuFcqBg/Dv3PhAR1+M5QOG6kOu9bUcOqboqY1nSC1sJMSN+7UIL9fIyQoSkyFsIhHN/V/R344vAOhSjvadryQRNs0bQhxucwgCI4x8LhW7OyulZeHstM/6dN0mmqE1lvtsmOsYeDGP1p/N9iUPPOpIVmWZ6IAnbfEWujFlkL0KLV92APrO2FyV8RglHSpaMZEMAmg3vUC/WQmGIWbwZe2EBWXAy3LZPIKh4ZhGedp6sWfiJypYQCPQz1GEJzgXlSurXDJYU+2Ge/TY3UdJ/J4/xJRK3F6FU1dNlY3fMgvo8Po/dFzjnEKppKtGUmRNfARCzrxAp6jE6VTD3p+vedah6CxUGEuUASzB9qDModLMQh1BNsJmWp849eIawErVenLh5jbK2ntwS4idiT4S/1rpIt+2A2IzO/X5nJ6M1vKwNMZzg6gYENLXcUxVZIcp6JBHk0l46gCXH7rHCYFHEWaxZpD5xNQeXmoVTpYo5sAM68Mo8dKddyZ2ZNnZHcUACs=
  on:
    tags: true
    repo: urbas/deep_release_notes
    python: 3.6
